-- Quotation header extensions (party type + unregistered GST flags/rate).
-- Run DDL from PreRun/table035_Quotation_PartyType_ManualGst.sql via DbUp first.
--
-- Stored procedures are not fully scripted in this repo; apply the following in SSMS, then deploy.
--
-- =============================================================================
-- Table dbo.Quotation — columns (see table035 script):
--   PartyType                TINYINT NOT NULL DEFAULT 1   -- 1 = Registered, 2 = Un-Registered
--   UnregisteredPartyName    NVARCHAR(500) NULL
--   UnregisteredPartyAddress NVARCHAR(MAX) NULL
--   UnregisteredPartyPhone   NVARCHAR(50) NULL (see PreRun/table054_Quotation_UnregisteredPartyPhone.sql)
--   GstRate                  FLOAT NOT NULL DEFAULT 0
--   IGST                     BIT NOT NULL DEFAULT 0   -- apply IGST component at GstRate
--   CGST                     BIT NOT NULL DEFAULT 0
--   SGST                     BIT NOT NULL DEFAULT 0
--
-- p_Quotation_ins — add parameters (match BAL/DAL/BillingDAL.cs AddQuotation):
--   @partyType                TINYINT = 1
--   @unregisteredPartyName    NVARCHAR(500) = NULL
--   @unregisteredPartyAddress NVARCHAR(MAX) = NULL
--   @unregisteredPartyPhone   NVARCHAR(50) = NULL
--   @gstRate                  FLOAT = 0
--   @IGST                     BIT = 0
--   @CGST                     BIT = 0
--   @SGST                     BIT = 0
--
-- p_Quotation_upd — same parameters; UPDATE corresponding columns.
--
-- p_getQuotation_byId — SELECT must include (Dapper → QuotationDTO):
--   PartyType, UnregisteredPartyName, UnregisteredPartyAddress, UnregisteredPartyPhone,
--   GstRate, IGST, CGST, SGST
--
-- Legacy: use ISNULL(PartyType, 1) in SELECT if needed.
-- =============================================================================
USE [$AppDb$]
GO
