<?xml version="1.0" encoding="utf-8"?>
<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"  xmlns:util="urn:util-format">
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <style>
          #printArea {

          font-family: Arial;
          }
          .border-row, td,th  {
          border:solid 1px;
          font-size:11px
          vertical-align: center;
          padding:5px;

          }


          .text-center{
          text-align:center;
          }
          .noborder{border:none !important;}
          h5 {line-height:15pt;margin:0px;font-size:16px}
        </style>
      </head>
      <body>
        <div id="printArea">
          <table style="width: 100%" cellpadding="0" cellspacing="0">
            <tr>
              <td style="width: 20%" class="noborder">
                <h3>e-Way Bill</h3>
              </td>
              <td style="width: 20%;text-align:right;" class="noborder">
                <img style="width:150px;">
                  <xsl:attribute name="src">
                    <xsl:value-of select="concat('data:image/jpeg;base64,',NewDataSet/Table[1]/qrCode)"/>
                  </xsl:attribute>
                </img>

              </td>
            </tr>
          </table>
          <table style="width:100%; border-collapse:collapse;margin-top:0px;"  class="mt-5">
            <tr>
              <td colspan="3" >
                <h5>1. E-Way Bill Details</h5>
              </td>
            </tr>
            <tr class="border-row">
              <td style="width:33%">
                e-Way Bill No: <xsl:value-of select="NewDataSet/Table[1]/ewayBillNo" />
              </td>
              <td style="width:33%">
                Generated Date:  <xsl:value-of select="util:DateToDDMMYYYY(NewDataSet/Table[1]/ewayBillDate)"/>
              </td>
              <td>
                Generated By:  <xsl:value-of select="NewDataSet/Table[1]/Company" />
              </td>
            </tr>
            <tr class="border-row">
              <td style="width:33%">
                Mode:Road
              </td>
              <td style="width:33%">
                Approx. Distance: <xsl:value-of select="NewDataSet/Table[1]/Distance" />KM
              </td>
              <td>
              </td>
            </tr>
            <tr class="border-row">
              <td style="width:33%">
                Type: 
                <xsl:choose>
                  <xsl:when test="NewDataSet/Table[1]/docSubType = 'ret'">
                    Inward
                  </xsl:when>
                  <xsl:otherwise>
                    Outward
                  </xsl:otherwise>
                </xsl:choose>
              </td>
              <td style="width:33%">
                Document Details: 
                <xsl:value-of select="NewDataSet/Table[1]/InvoiceNumber" /> - <xsl:value-of select="util:DateToDDMMYYYY(NewDataSet/Table[1]/InvoiceDate)" />
              </td>
              <td>
                Transaction Type:Regular
              </td>
            </tr>
          </table>
          <table style="width:100%;border-collapse:collapse;margin-top:10px;"  >
            <tr>
              <td colspan="2" >
                <h5>2. Address Details</h5>
              </td>
            </tr>
            <tr>
              <td>From</td>
              <td>To</td>
            </tr>
            <tr>
              <td>
                GSTIN: <xsl:value-of select="NewDataSet/Table[1]/CompanyGST" /><br/>
                <xsl:value-of select="NewDataSet/Table[1]/Company" /><br/>
                <xsl:value-of select="NewDataSet/Table[1]/CompanyCity" /> ( <xsl:value-of select="NewDataSet/Table[1]/CompanyState" />)<br/>
                Dispatch From:<br/>
                <xsl:value-of select="NewDataSet/Table[1]/CompanyAddress" /><br/>
                <xsl:value-of select="NewDataSet/Table[1]/CompanyCity" />
                <xsl:text> </xsl:text><xsl:value-of select="NewDataSet/Table[1]/CompanyZipCode" />
                <xsl:text> </xsl:text>(<xsl:value-of select="NewDataSet/Table[1]/CompanyState" />)
              </td>
              <td>
                GSTIN: <xsl:value-of select="NewDataSet/Table[1]/ClientGST" /><br/>
                <xsl:value-of select="NewDataSet/Table[1]/Client" /><br/>
                <xsl:value-of select="NewDataSet/Table[1]/ClientCity" /> ( <xsl:value-of select="NewDataSet/Table[1]/ClientState" />)<br/>
                Ship To:<br/>
                <xsl:value-of select="NewDataSet/Table[1]/ClientShipAddress" /><br/>
                <xsl:value-of select="NewDataSet/Table[1]/ClientShipCity" />
                <xsl:text> </xsl:text><xsl:value-of select="NewDataSet/Table[1]/ClientShipZipCode" />
                <xsl:text> </xsl:text>(<xsl:value-of select="NewDataSet/Table[1]/ClientShipState" />)
              </td>
            </tr>
          </table>
          <table style="width:100%; border-collapse:collapse;margin-top:10px;"  >
            <tr>
              <td colspan="12" >
                <h5>3. Goods Details</h5>
              </td>
            </tr>
            <tr>
              <th>HSN Code</th>
              <th colspan="4">Product Name  Desc.</th>
              <th  class="text-right">Quantity</th>
              <th  class="text-right">Taxable Amount (rs)</th>
              <th  class="text-center" colspan="5">Tax Rate(C+S+I+Cess+Cess Non. Advol)</th>
            </tr>
            <xsl:for-each select="NewDataSet/Table">
              <tr>
                <td>
                  <xsl:value-of select="HSNCode" />
                </td>
                <td colspan="4">
                  <xsl:value-of select="Item" />
                </td>
                <td class="text-right">
                  <xsl:value-of select="Quantity" />
                </td>
                <td class="text-right"> 
                  <xsl:value-of select="SubTotal" />
                </td>
                <td  class="text-right">
                  <xsl:value-of select="CGSTRate" />%
                </td >
                <td  class="text-right">
                  <xsl:value-of select="SGSTRate" />%
                </td>
                <td  class="text-right">
                  <xsl:value-of select="IGSTRate" />%
                </td>
                <td class="text-right" >
                  0%
                </td>
                <td  class="text-right">
                  0
                </td>
              </tr>
            </xsl:for-each>
            <tr>
              <th class="text-center" >Total. Taxable Amt </th>
              <th class="text-center">CGST Amt </th>
              <th class="text-center">SGST Amt </th>
              <th class="text-center">IGST Amt </th>
              <th class="text-center">CESS Amt</th>
              <th class="text-center">Cess Non. Advol Amt</th>
              <th class="text-center">Other Amt.</th>
              <th colspan="5" class="text-center">Total. Inv. Amt</th>


            </tr>
            <tr>
              <td class="text-center">
                <xsl:value-of select="sum(NewDataSet/Table/SubTotal)"/>
              </td>

              <td class="text-center">
                <xsl:value-of select="sum(NewDataSet/Table/CGST)"/>
              </td>
              <td class="text-center">
                <xsl:value-of select="sum(NewDataSet/Table/SGST)"/>
              </td>
              <td class="text-center">
                <xsl:value-of select="sum(NewDataSet/Table/IGST)"/>
              </td>
              <td class="text-center">
               0
              </td>
              <td class="text-center">
              0
              </td>
              <td class="text-center">
                0
              </td>
              <td colspan="5" class="text-center">
                <xsl:choose>
                  <xsl:when test="number(NewDataSet/Table[1]/ApproximateValue) &gt; 0">
                    <xsl:value-of select="NewDataSet/Table[1]/ApproximateValue"/>
                  </xsl:when>
                  <xsl:otherwise>
                    <xsl:value-of  select="sum(NewDataSet/Table/SubTotal) + sum(NewDataSet/Table/CGST) + sum(NewDataSet/Table/SGST) + sum(NewDataSet/Table/IGST)"/>
                  </xsl:otherwise>
                </xsl:choose>
              </td>
            </tr>
          </table>
          <table style="width:100%;border:solid 1px;border-collapse:collapse;margin-top:10px;"  >
            <tr>
              <td colspan="8" >
                <h5>4. Transporter Details</h5>
              </td>

            </tr>
            <tr>
              <td colspan="4">
                Transporter ID and Name:  <xsl:value-of select="NewDataSet/Table[1]/TransporterGST"/>/
                <xsl:value-of select="NewDataSet/Table[1]/TransporterName"/>
              </td>
              <td colspan="4">Transport Doc No. and Date: </td>

            </tr>
            <tr>
              <th>Mode </th>
              <th>Vehicle/Transport Doc. No and Date </th>
              <th>Quantity</th>
              <th>Entered Date </th>
              <th class="text-center">Entered By</th>
              <th>CEWB No. (If any)</th>
              <th colspan="2">Multi Veh.Ino (If any)</th>

            </tr>
            <tr>
              <td>
                <xsl:value-of select="NewDataSet/Table[1]/TransportationMode"/>
              </td>
              <td>
                <xsl:value-of select="NewDataSet/Table[1]/VehicleNo"/>
              </td>
              <td class="text-center">
                <xsl:value-of select="sum(NewDataSet/Table/Quantity)"/>
              </td>
              <td>
                <xsl:value-of select="util:DateToDDMMYYYY(NewDataSet/Table[1]/ewayBillDate)"/>
              </td>
              <td class="text-center">
                <xsl:value-of select="NewDataSet/Table[1]/Company"/>
              </td>
              <td></td>
              <td></td>
              <td colspan="2"></td>

            </tr>
          </table>
        </div>

      </body>
    </html>

  </xsl:template>
</xsl:transform>
