<?xml version="1.0" encoding="utf-8"?>
<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"  xmlns:util="urn:util-format">
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <style>
          #printArea {

          font-family: Arial;
          }
          .border-row, td,th  {
          border:solid 1px;
          font-size:11px
          vertical-align: center;
          padding:5px;

          }


          .text-center{
          text-align:center;
          }
          .noborder{border:none !important;}
          h5 {line-height:15pt;margin:0px;font-size:16px}
        </style>
      </head>
      <body>
        <div id="printArea">
          <table style="width: 100%" cellpadding="0" cellspacing="0">
            <tr>
              <td colspan="8" class="noborder text-center">
                <h3>e-Way Bill</h3>
                <div>
                  <img style="width:150px;">
                    <xsl:attribute name="src">
                      <xsl:value-of select="concat('data:image/jpeg;base64,',NewDataSet/Table[1]/qrCode)"/>
                    </xsl:attribute>
                  </img>
                </div>
              </td>

            </tr>
            <tr>
              <td colspan="2">E-Way Bill No:</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table[1]/ewayBillNo" />
              </td>
            </tr>
            <tr>
              <td colspan="2">E-Way Bill Date:</td>
              <td colspan="6">
                <xsl:value-of select="util:DateToDDMMYYYY(NewDataSet/Table[1]/ewayBillDate)"/>
              </td>
            </tr>
            <tr>
              <td colspan="2">Generated By</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table[1]/generatedByGST" />,   <xsl:value-of select="NewDataSet/Table[1]/generatedBy" />
              </td>
            </tr>
            <tr>
              <td colspan="2">Valid From:</td>
              <td colspan="6">
                <xsl:value-of select="util:DateToDDMMYYYY(NewDataSet/Table[1]/ewayBillDate)"/>
                [<xsl:value-of select="util:NumberValueFromString(NewDataSet/Table[1]/ewayBillAlert)"/> Kms]
              </td>
            </tr>
            <tr>
              <td colspan="2">Valid Until:</td>
              <td colspan="6">
                <xsl:value-of select="util:DateToDDMMYYYY(NewDataSet/Table[1]/ewayBillValidUpTo)"/>
              </td>
            </tr>
            <tr>
              <td colspan="2">Portal:</td>
              <td colspan="6">1</td>
            </tr>
            <tr>
              <td colspan="8">
                <strong>Part - A</strong>
              </td>
            </tr>
            <tr>
              <td colspan="2">GSTIN Of Supplier</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table[1]/CompanyGST" />
              </td>
            </tr>
            <tr>
              <td colspan="2">Place of Dispatch</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table[1]/CompanyCity" />
                <xsl:text> </xsl:text><xsl:value-of select="NewDataSet/Table[1]/CompanyZipCode" />
                <xsl:text> </xsl:text>(<xsl:value-of select="NewDataSet/Table[1]/CompanyState" />)
              </td>
            </tr>
            <tr>
              <td colspan="2">GSTIN of Recipient</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table[1]/ClientGST" />
                | <xsl:text> </xsl:text>  <xsl:value-of select="NewDataSet/Table/ClientTradeName" />
              </td>
            </tr>
            <tr>
              <td colspan="2">Place of Delivery</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table[1]/ClientShipCity" />
                <xsl:text> </xsl:text><xsl:value-of select="NewDataSet/Table[1]/ClientShipZipCode" />
                <xsl:text> </xsl:text>(<xsl:value-of select="NewDataSet/Table[1]/ClientShipState" />)

              </td>
            </tr>
            <tr>
              <td colspan="2">Document No.</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table[1]/InvoiceNumber" />
              </td>
            </tr>
            <tr>
              <td colspan="2">Document Date</td>
              <td colspan="6">
                <xsl:value-of select="util:DateToDDMMYYYY(NewDataSet/Table[1]/InvoiceDate)" />
              </td>
            </tr>
            <tr>
              <td colspan="2">Transaction Type</td>
              <td colspan="6">
                <xsl:choose>
                  <xsl:when test="NewDataSet/Table/transactionType = 1">Regular</xsl:when>
                  <xsl:when test="NewDataSet/Table/transactionType = 2">Bill To - Ship To</xsl:when>
                  <xsl:when test="NewDataSet/Table/transactionType = 3">Bill From - Dispatch From</xsl:when>
                  <xsl:otherwise>
                    Combination of 2 and 3
                  </xsl:otherwise>
                </xsl:choose>

              </td>
            </tr>
            <tr>
              <td colspan="2">Value of Goods</td>
              <td colspan="6">
                <xsl:choose>
                  <xsl:when test="number(NewDataSet/Table/ApproximateValue) &gt; 0">
                    <xsl:value-of select="NewDataSet/Table/ApproximateValue"/>
                  </xsl:when>
                  <xsl:otherwise>
                    <xsl:value-of  select="sum(NewDataSet/Table/SubTotal) + sum(NewDataSet/Table/CGST) + sum(NewDataSet/Table/SGST) + sum(NewDataSet/Table/IGST)"/>
                  </xsl:otherwise>
                </xsl:choose>
              </td>
            </tr>
            <tr>
              <td colspan="2">HSN Code</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table/HSNCode" /> -
                <xsl:choose>
                  <xsl:when test="count(NewDataSet/Table[IsBomItem = 1]/Item) > 0">
                    <xsl:value-of select="NewDataSet/Table[IsBomItem=1]/Item" />
                  </xsl:when>
                  <xsl:otherwise>
                    <xsl:value-of select="NewDataSet/Table/Item" />
                  </xsl:otherwise>
                </xsl:choose>

              </td>
            </tr>
            <tr>
              <td colspan="2">Reason for Transportation</td>
              <td colspan="6">
                <xsl:choose>
                  <xsl:when test="NewDataSet/Table[1]/docSubType = 'ret'">
                    Inward
                  </xsl:when>
                  <xsl:otherwise>
                    Outward
                  </xsl:otherwise>
                </xsl:choose>
                <xsl:text> </xsl:text>
                <xsl:value-of select="NewDataSet/Table[1]/otherTypeDesc"/>
              </td>
            </tr>
            <tr>
              <td colspan="2">Transporter</td>
              <td colspan="6">
                <xsl:value-of select="NewDataSet/Table[1]/TransporterGST"/>/
                <xsl:value-of select="NewDataSet/Table[1]/TransporterName"/>
              </td>
            </tr>
            <tr>
              <td colspan="8">
                <strong>Part - B</strong>
              </td>
            </tr>
            <tr>
              <td>Mode</td>
              <td>
                Vehicle / Trans
                Doc No   Dt.
              </td>
              <td>
                From
              </td>
              <td>
                Entered Date
              </td>
              <td>
                Entered By
              </td>
              <td>
                CEWB No.
                (If any)
              </td>
              <td>
                Multi Veh. Info
                (If any)
              </td>
              <td>
                Portal
              </td>
            </tr>
            <tr>
              <td>
                <xsl:value-of select="NewDataSet/Table[1]/TransportationMode"/>
              </td>
              <td>
                <xsl:value-of select="NewDataSet/Table[1]/VehicleNo"/>

              </td>
              <td>
                <xsl:value-of select="NewDataSet/Table[1]/CompanyCity" />
              </td>
              <td>
                <xsl:value-of select="util:DateToDDMMYYYY(NewDataSet/Table[1]/ewayBillDate)"/>
              </td>
              <td>
                <xsl:value-of select="NewDataSet/Table[1]/generatedByGST" />
              </td>
              <td>
                -
              </td>
              <td>
                -
              </td>
              <td>
                1
              </td>
            </tr>
            <tr>
              <td colspan="8"></td>
            </tr>
            <tr>
              <td colspan="8">
                Note*: If any discrepancy in information please try after sometimes.
              </td>
            </tr>
          </table>

        </div>

      </body>
    </html>

  </xsl:template>
</xsl:transform>
